name: Run Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Use Node.js 18.x which fully supports ReadableStream

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: the-best-trio  # Specify the working directory

      - name: Run index.js
        run: node index.js
        working-directory: the-best-trio  # Specify the working directory
