name: Run Node.js App with ngrok

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # Use Node.js 18.x which fully supports ReadableStream

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: the-best-trio  # Specify the working directory

      - name: Install ngrok
        run: npm install -g ngrok

      - name: Start Node.js server in background
        run: node index.js &
        working-directory: the-best-trio

      - name: Start ngrok to expose port 3028
        run: ngrok http 3028

      - name: Display ngrok public URL
        run: curl http://127.0.0.1:4040/api/tunnels
